server:
  port: 9527

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从服务注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: user_service1 #路由ID,要求唯一
          uri: lb://user-service #匹配后提供路由的服务地址  ws://->websocket , lb://->微服务(实现负载均衡) , http://->http
#          uri: http://localhost:8001 #匹配后提供路由的服务地址
          predicates: #断言，路径相匹配的进行路由
            - Path=/users/**

        - id: user_service2
          uri: lb://user-service
          predicates:
            - Path=/common/**

        - id: shipping_service1
          uri: lb://shipping-service
          predicates:
            - Path=/orders/**

        - id: shipping_service2
          uri: lb://shipping-service
          predicates:
            - Path=/products/**

        - id: shipping_service3
          uri: lb://shipping-service
          predicates:
            - Path=/sites/**

        - id: auth_service1
          uri: lb://auth-service
          predicates:
            - Path=/oauth/**

eureka:
  instance:
    instance-id: gateway9527
    prefer-ip-address: true #访问路径显示ip地址
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #服务注册地址
      defaultZone: http://localhost:7001/eureka/
