server:
  port: 8004

spring:
  application:
    name: auth-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样介于0~1之间，1表示全部采样
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stmdb?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hny.entity


eureka:
  instance:
    instance-id: auth8004
    prefer-ip-address: true #访问路径显示ip地址
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #服务注册地址
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: true
